### ISSUE TITLE
No Building Walls?

### ISSUE THREAD

**Issue by Bj007pro** [DigiWorm0/LevelImposter#14]
I looked through all categories in the editor and couldn't find them.
Did I miss them when I looked, or they're not there?

**Comment by DigiWorm0** [comment]
Walls are provided under each object as **Colliders**. I suggest you review the [LevelImposter Docs](https://levelimposter.net/Docs/) under **Making Colliders** for more information.

**Comment by Bj007pro** [comment]
> Walls are provided under each object as **Colliders**. I suggest you review the [LevelImposter Docs](https://levelimposter.net/Docs/) under **Making Colliders** for more information.

I'm sorry, but I think you closed this issue way too quickly.
That part in the help document is telling me how to make collisions with already created rooms/objects.

I was asking about vertical and horizontal walls, as well as corners to create custom buildings.
And if the help document does tell me how then I'm not understanding it.
