### ISSUE TITLE
THE MAP IS NOT LOADING

### ISSUE THREAD

**Issue by NotGamerPro** [DigiWorm0/LevelImposter#2]
When I open among us it's still the same map. Can you please fix this.
Thank you

**Comment by DigiWorm0** [comment]
Do you have BepInEx and Reactor installed?

Are you on Among Us 2021.3.31.3?

If the answer to both of these questions is yes, could you please provide log output?

**Comment by NotGamerPro** [comment]
Sorry. My version is 2021.3.31s
Can you say what version of LevelImposter I should use.
Thank you

**Comment by DigiWorm0** [comment]
You should always use the latest version of LevelImposter. Among Us 2021.3.31s should work fine. Is there any logs you can provide in order to debug this issue?
