### ISSUE TITLE
layer bug

### ISSUE THREAD

**Issue by Pietrodjaowjao** [DigiWorm0/LevelImposter#22]
i can't use layer things, and then starfield overrides all map, i tried to use layer folders but them didnt work

**Comment by DigiWorm0** [comment]
Your layer issue is unclear. What do you mean by "didn't work"? Layers are purely for organizational purposes, and don't raise or lower objects in the map. That is what Z-indes is for. 

Starfield will preview above all other elements, but it actually renders below them, that is a bug.

**Comment by Pietrodjaowjao** [comment]
oh sorry, i thinked layers are like photoshop ones
