### ISSUE TITLE
Add in Doucumention TownOfModrole mod 

### ISSUE THREAD

**Issue by Wael1231** [DigiWorm0/LevelImposter#30]
hey @DigiWorm0 i swear LevelImpostor is the best mod that i test 🥇 . its very cool i test it with my mod in private it work fine and i wante if you can add in documention TownOfModrole mod Coming Soon and thanks for all 👍 .

if you see this message make sure ping me

**Comment by DigiWorm0** [comment]
Thank you, but we will not be adding "TownOfModrole" to our Mod Compatibility list at this time. I appreciate your understanding.

**Comment by Wael1231** [comment]
oh i see it allowed that to launch a mod with LevelImpostor mod ?
