### ISSUE TITLE
The mod's main functionality (custom maps) literally broke (it defaults to Mira HQ)

### ISSUE THREAD

**Issue by yayy80** [DigiWorm0/LevelImposter#37]
## What Happened?
All the maps default to Mira HQ (on the latest among us version), and on the older one it does work but crashes shortly after.

## What Should Have Happened?
Even if I downgrade versions- it still crashes whenever I try to open a map.

## Versions
- **LevelImposter:** LATEST
- **Among Us:** LATEST

**Comment by DigiWorm0** [comment]
At the moment, the latest LevelImposter only supports Among Us v2023.11.28. We're working on getting updated to v2024.3.5. You can also downgrade your Among Us version until we're back up to date.

**Comment by yayy80** [comment]
I figured that out actually.
