### ISSUE TITLE
my among us version doesnt support

### ISSUE THREAD

**Issue by jiggusuperking** [DigiWorm0/LevelImposter#39]
my among us version is 2024.3.5 
pls update the mod to work : 2024.3.5 
i need levelimposter mod in 2024.3.5

**Comment by Yougha789** [comment]
Bonjour ,
Quand sortira le mod en 2024.3.5 ?

Bonne journée

**Comment by GameTechGuides** [comment]
bro check branch dev and get dll from actions

**Comment by DigiWorm0** [comment]
Updated to Among Us v2024.3.5 & v2024.6.4 w/ v0.19.0
