### ISSUE TITLE
Warning Sign Forever Existent 

### ISSUE THREAD

**Issue by zeldaking** [DigiWorm0/LevelImposter#7]
So when I finished my map I opened up the warning and finished them but then the window for the warnings would not go away even though there are no warnings there and now I can't save my map. I put 2 hours into it and I want to be able to export it so I can play. PLS HELP D;

**Comment by DigiWorm0** [comment]
This is a known bug. If you create another warning, you can close the warnings window then resolve the warning with the window closed.

**Comment by zeldaking** [comment]
ok thanks
